version: 1
type: maven
resolver:
  serverId: art
  snapshotRepo: libs-snapshots
  releaseRepo: libs-releases
deployer:
  serverId: art
  snapshotRepo: libs-snapshots-local
  releaseRepo: libs-release-local