resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_drorb
      path: drorb/project-examples
pipelines:
  - name: pipeline_maven_example
    steps:
      - name: step_install
        type: MvnBuild
        configuration:
          mvnCommand: install
          sourceLocation: maven-example
          configFileLocation: .
          configFileName: mvn-art-config.yml
          autoPublishBuildInfo: true
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
