resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_drorb
      path: drorb/project-examples
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art 
pipelines:
  - name: pipeline_maven_example
    steps:
      - name: step_install
        type: MvnBuild
        configuration:
          mvnCommand: install publish
          sourceLocation: maven-example
          configFileLocation: .
          configFileName: mvn-art-config.yml
          autoPublishBuildInfo: true
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: step_install
          outputResources:
            - name: appl_build_info
