resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_drorb
      path: drorb/project-examples
pipelines:
  - name: pipeline_maven_example
    steps:
      - name: install
        type: MvnBuild
        mvnCommand: install
        sourceLocation: maven-example
        configFileLocation: .
        configFileName: pom.xml
        integrations:
            - name: art
