pipelines:
  - name: pipeline_maven_example
    steps:
      - name: install
        type: MvnBuild
        mvnCommand: install
        sourceLocation: maven-example
        configFileLocation: .
        configFileName: pom.xml
