resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_drorb
      path: drorb/project-examples
  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art 
      buildName: maven-example
      buildNumber: 0
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art 
      buildName: npm-example
      buildNumber: 0
pipelines:
  - name: pipeline_maven_example
    steps:
      - name: step_install
        type: MvnBuild
        configuration:
          mvnCommand: clean test install
          sourceLocation: maven-example
          configFileLocation: .
          configFileName: mvn-art-config.yml
          autoPublishBuildInfo: true
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
          outputResources:
            - name: mvn_build_info
        execution:
            onComplete:
              - save_tests $res_myAppRepo_resourcePath/maven-example/multi1/target/surefire-reports
              - save_tests $res_myAppRepo_resourcePath/maven-example/multi2/target/surefire-reports
              - save_tests $res_myAppRepo_resourcePath/maven-example/multi3/target/surefire-reports
      - name: step_xray_scan
        type: XrayScan
        configuration:
          failOnScan: true
          inputResources:
            - name: mvn_build_info
              trigger: true
  - name: pipeline_npm_example
    steps:
      - name: step_install
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: npm-example
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
      - name: step_publish
        type: NpmPublish
        configuration:
          repositoryName: npm-virtual
          forceXrayScan: true
          autoPublishBuildInfo: true
          integrations:
              - name: art
          inputSteps:
            - name: step_install
          outputResources:
            - name: npm_build_info
          
