resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_drorb
      path: drorb/project-examples
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art 
      buildName: maven-example
      buildNumber: 0
pipelines:
  - name: pipeline_maven_example
    steps:
      - name: step_install
        type: MvnBuild
        configuration:
          mvnCommand: install
          sourceLocation: maven-example
          configFileLocation: .
          configFileName: mvn-art-config.yml
          autoPublishBuildInfo: true
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
          outputResources:
            - name: appl_build_info
  - name: pipeline_npm_example
    steps:
      - name: step_install
        type: NpmBuild
        configuration:
          npmArgs: --verbose
          repositoryName: npm-local
          sourceLocation: npm-example
          integrations:
              - name: art
          inputResources:
              - name: myAppRepo
          
